Extend test-code sources to use __LOC__ macros. Fix Make, Py-gen issues
This commit mildly overhauls Makefile-rules to build test-code
program sources that are now extended to use __LOC__ macros.

gen_loc_files.py:
 - Fix CFLAGS to replace '-', with '_' (underscore).
 - Generate #include inttypes.h in loc.h, to remove compiler
   error: unknown type name 'uint32_t'

test-code:
 - Extend sample program sources to demonstrate different
   applications of __LOC__ macro

Makefile:
 - Rework the rules to add dependency of test-code program
   sources on their respective generated LOC-files
 - Fix rules to correctly compild-and-build changed test-code
   which now require loc* files.

Extend single-file-main.c to use __LOC__ macros. Fix build issues.

- Update single-file-main.c to use __LOC__ encoding macro
  in couple of different ways.
- Fix generator to also substitute '-' in filename with '_'
- Update Makefile to handle single-file-program.c and its
  compilation
- Move debug print code so it's emitted only once. Hacky-fix.

Minor edits.